version: '3.8'

services:
  backend:
    build: .
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8888", "--reload"]
    volumes:
      - ./:/app
    ports:
      - "8888:8888"

  frontend:
    build: .
    command: ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8888
    depends_on:
      - backend 