method: bayes
metric:
  goal: maximize
  name: best_val_r2
parameters:
  batch_size:
    values:
    - 512
    - 1024
    - 2048
  domain_emb_dim:
    values:
    - 16
    - 32
    - 64
  dropout_rate:
    distribution: uniform
    max: 0.5
    min: 0.1
  hidden_dim:
    values:
    - 128
    - 256
    - 512
  learning_rate:
    distribution: uniform
    max: 0.05
    min: 0.0001
  patience:
    values:
    - 5
    - 10
    - 15
  scheduler_factor:
    values:
    - 0.1
    - 0.5
  user_emb_dim:
    values:
    - 32
    - 64
    - 128
  weight_decay:
    distribution: log_uniform_values
    max: 0.001
    min: 1.0e-06